name: publish-untested
on: 
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to release'     
        required: true

jobs:
  call-workflow:
    uses: splunk/github-workflow-publish-manual/.github/workflows/reusable-publish-manual.yaml@v1.0.0
    secrets:
      GH_TOKEN_ADMIN: ${{ secrets.GH_TOKEN_ADMIN }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
